name: linter

on:
  push:
    branches: [develop, main]
  pull_request:
    branches: [develop, main]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ github.ref != 'refs/heads/main' }}

jobs:
  lint-backend:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.4'

      - name: Install Dependencies
        run: composer install -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist

      - uses: actions/upload-artifact@v4
        with:
          name: vendor
          path: vendor/

      - name: Run Rector
        run: composer test:refactor

      - name: Run PHPStan
        run: composer test:types

      - name: Run Pint
        run: composer test:lint

  lint-frontend:
    needs: [lint-backend]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: actions/download-artifact@v4
        with:
          name: vendor
          path: vendor/

      - name: Install Dependencies
        run: npm ci

      - name: Run Eslint
        run: npm run lint

      - name: Run Prettier
        run: npm run test:format

      - name: Run Typescript
        run: npm run test:types
